---
- name: Build and Run Flask Container
  hosts: azurehosts
  remote_user: azureuser
  gather_facts: false
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
---
- name: Build and Run Flask Container
  hosts: azurehosts
  remote_user: azureuser
  gather_facts: false
  become: yes

  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Copy Flask app files to VM
      copy:
        src: ~/workspace/Issue_Tracker
        dest: /var/www/flask_app
    

    - name: Stop and Remove Existing Docker container
      become: true
      shell: docker rm -f flask-container
      ignore_errors: yes

    - name: Build Docker image
      become: true
      shell: docker build -t my-flask-app /var/www/flask_app/Issue_Tracker

    - name: Run Docker container
      become: true
      shell: docker run -d --name flask-container -p 8000:8000 --restart always my-flask-app

    