---
- name: Build and Run Flask Container
  hosts: azurehosts
  remote_user: azureuser
  become: yes
  ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    # - name: Copy Flask app files to VM
    #   copy:
    #     src: ~/Documents/Github/Issue_Tracker
    #     dest: /var/www/flask_app
    - name: Stop Docker container
      docker_container:
        name: flask-container
        image: my-flask-app
        state: stopped  
    
    - name: Build Docker image
      docker_image:
        name: my-flask-app
        source: build
        build:
          path: /var/www/flask_app/Issue_Tracker
        state: present   

    

    - name: Run Docker container
      docker_container:
        name: flask-container
        image: my-flask-app
        ports:
          - "8000:8000"
        state: started  
        restart_policy: always