---
- name: Setup Flask App on VM
  hosts: your_vm_hostname_or_ip
  become: yes

  tasks:
    - name: Install Python and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Create a virtual environment
      command: virtualenv /var/www/flask_app/venv
      args:
        creates: /var/www/flask_app/venv

    - name: Copy Flask app files to VM
      copy:
        src: ~/Documents/Github/Issue_Tracker/
        dest: /var/www/flask_app/Issue_Tracker
      remote_src: yes

    - name: Activate virtual environment
      command: source /var/www/flask_app/venv/bin/activate

    - name: Install Flask and dependencies
      pip:
        requirements: /var/www/flask_app/Issue_Tracker/requirements.txt

    - name: Start the Flask app
      command: /var/www/flask_app/venv/bin/python /var/www/flask_app/Issue_Tracker/app.py
      async: 0
      poll: 0
