---
- name: Install Flask server on VM
  hosts: webserver  # Replace with the target VM's hostname or IP address
  become: yes         # Run tasks with sudo

  tasks:
    # Update apt cache (for Debian/Ubuntu) or yum cache (for CentOS/RHEL)
    - name: Update package cache
      become: yes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install required packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-venv
        - nginx
      when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install required packages
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-virtualenv
        - nginx
      when: ansible_os_family == 'RedHat' or ansible_distribution == 'CentOS'

    - name: Create Flask app directory
      become: yes
      file:
        path: /var/www/flask_app
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    # - name: Copy Flask app files
    #   become: yes
    #   copy:
    #     src: ~/Documents/Github/Issue_Tracker/ # Replace with the path to your Flask app files
    #     dest: /var/www/flask_app/Issue_Tracker/
    #     owner: azureuser
    #     group: azureuser

    - name: Set up virtual environment
      become: yes
      command: python3 -m venv /var/www/flask_app/Issue_Tracker/venv

    - name: Install Flask and required packages
      become: yes
      pip:
        requirements: /var/www/flask_app/Issue_Tracker/requirements.txt
        virtualenv: /var/www/flask_app/Issue_Tracker/venv

    - name: Run Python application
      command: /usr/bin/python3 /var/www/flask_app/Issue_Tracker/app.py

  